spring:
  profiles:
    active: dev
#    active: prod
  servlet:
    multipart:
      location: D:/tomcat/

swagger:
  production: false
  basic:
    enable: false
    username: aadmin
    password: 123456
